import type {
  AdminAccessDecisionSummary, AdminAccessGrantDetail, AdminAdminActionItem, AdminAssessmentDetail, AdminAuditLogItem,
  AdminContentTreeNode, AdminDeviceSummary, AdminLessonDetail, AdminMediaAssetDetail, AdminPaymentDetail,
  AdminPlaybackSessionSummary, AdminPolicySetSummary, AdminRefundDetail, AdminRoleSummary, AdminSecurityEventItem, AdminSessionSummary,
  AdminStudentDetail, AdminSubscriptionDetail, AdminSeatSummary, AdminAttemptDetail,
  AdminUserSummary, AdminPlatformContext, AdminBrandContext,
} from "./adminApi.types";
import { eliteOverviewDashboard, medwayOverviewDashboard } from "./adminOverview.fixtures";

// Canonical brand identities. Platform exports below are compatibility aliases only.
export const medwayBrand: AdminBrandContext = { brandId: "platform-medway", brandCode: "medway", brandDisplayName: "Medway", platformId: "platform-medway", platformCode: "medway" };
export const eliteBrand: AdminBrandContext = { brandId: "platform-elite", brandCode: "elite", brandDisplayName: "Elite", platformId: "platform-elite", platformCode: "elite" };
export const nexusBrand: AdminBrandContext = { brandId: "platform-nexus", brandCode: "nexus", brandDisplayName: "Nexus", platformId: "platform-nexus", platformCode: "nexus" };
/** @deprecated Compatibility alias only. Medway is a brand, not a separate platform. */
export const medwayPlatform: AdminPlatformContext = { platformId: medwayBrand.brandId, platformCode: medwayBrand.brandCode, platformDisplayName: medwayBrand.brandDisplayName };
/** @deprecated Compatibility alias only. Elite is a brand, not a separate platform. */
export const elitePlatform: AdminPlatformContext = { platformId: eliteBrand.brandId, platformCode: eliteBrand.brandCode, platformDisplayName: eliteBrand.brandDisplayName };
export const nexusPlatform: AdminPlatformContext = { platformId: nexusBrand.brandId, platformCode: nexusBrand.brandCode, platformDisplayName: nexusBrand.brandDisplayName };

const medDate = "2026-08-19T09:00:00.000Z";
const eliteDate = "2026-08-19T10:00:00.000Z";
const privateRef = (referenceId: string) => ({ referenceId, providerLabel: "drive-import-reference", isPublic: false as const, redaction: "private_storage_reference" as const });

export interface AdminFixtureBundle {
  platform: AdminPlatformContext;
  overview: import("./adminApi.types").AdminOverviewDashboard;
  students: readonly AdminStudentDetail[];
  devices: readonly AdminDeviceSummary[];
  sessions: readonly AdminSessionSummary[];
  payments: readonly AdminPaymentDetail[];
  refunds: readonly AdminRefundDetail[];
  subscriptions: readonly AdminSubscriptionDetail[];
  seats: readonly AdminSeatSummary[];
  accessGrants: readonly AdminAccessGrantDetail[];
  contentTree: readonly AdminContentTreeNode[];
  lessons: readonly AdminLessonDetail[];
  mediaAssets: readonly AdminMediaAssetDetail[];
  accessDecisions: readonly AdminAccessDecisionSummary[];
  playbackSessions: readonly AdminPlaybackSessionSummary[];
  assessments: readonly AdminAssessmentDetail[];
  attempts: readonly AdminAttemptDetail[];
  auditLogs: readonly AdminAuditLogItem[];
  securityEvents: readonly AdminSecurityEventItem[];
  adminActions: readonly AdminAdminActionItem[];
  roles: readonly AdminRoleSummary[];
  adminUsers: readonly AdminUserSummary[];
  policySets: readonly AdminPolicySetSummary[];
}

const medStudents: AdminStudentDetail[] = [1, 2, 3, 4].map((n) => ({
  id: `med-user-00${n}`, platform: medwayPlatform, displayName: ["Mariam Hassan", "Omar Nabil", "Salma Adel", "Youssef Karim"][n - 1],
  emailMasked: `student${n}@m***.edu`, phoneMasked: "+20 *** *** **" + n, academicTermOrYear: n < 3 ? "Level 1 / Semester 1" : "Level 2 / Semester 3", university: "BUC Medicine", studentIdMasked: `BUC-****-${n}`,
  status: n === 4 ? "suspended" : "active", activeSubscriptionCount: n === 4 ? 0 : 1, activeGrantCount: n === 4 ? 0 : 1, activeDeviceCount: 1, activeSessionCount: n === 2 ? 2 : 1, lastSeenAt: medDate,
  riskFlags: n === 2 ? ["multiple_active_sessions", "concurrent_playback_conflict"] : n === 4 ? ["suspicious_access_denials"] : ["none"],
  createdAt: "2026-07-01T09:00:00.000Z", updatedAt: medDate,
  access: { activeSubscriptionCount: n === 4 ? 0 : 1, activeSeatCount: n === 3 ? 1 : 0, activeGrantCount: n === 4 ? 0 : 1, expiredGrantCount: n === 3 ? 1 : 0, revokedGrantCount: n === 4 ? 1 : 0, enrollmentCount: n === 4 ? 0 : 1 },
  learning: { enrollmentCount: n === 4 ? 0 : 1, completedLessonCount: n, attemptCount: n + 1, playbackSessionCount: n === 2 ? 2 : 1, lastLearningActivityAt: medDate },
  devices: [], sessions: [],
}));

const medDevices: AdminDeviceSummary[] = [1, 2, 3, 4].map((n) => ({ id: `med-device-00${n}`, platform: medwayPlatform, userId: `med-user-00${n}`, deviceLabel: n === 2 ? "Mobile and browser" : "Primary browser", deviceType: n === 2 ? "mobile" : "browser", trustStatus: n === 4 ? "revoked" : n === 2 ? "suspicious" : "recognized", firstSeenAt: "2026-07-01T09:00:00.000Z", lastSeenAt: medDate, revokedAt: n === 4 ? medDate : null, fingerprintReference: `med-fingerprint-redacted-${n}` }));
const medSessions: AdminSessionSummary[] = [1, 2, 3, 4].map((n) => ({ id: `med-session-00${n}`, platform: medwayPlatform, userId: `med-user-00${n}`, deviceId: `med-device-00${n}`, status: n === 4 ? "revoked" : "active", issuedAt: "2026-08-19T08:00:00.000Z", expiresAt: "2026-08-19T20:00:00.000Z", revokedAt: n === 4 ? medDate : null, lastActivityAt: medDate }));

const medPolicy = (n: number, name: string): AdminPolicySetSummary => ({ id: `med-policy-00${n}`, platform: medwayPlatform, name, version: 1, effectiveFrom: "2026-01-01T00:00:00.000Z", effectiveTo: null, status: "active", documentReference: `med-policy-document-redacted-${n}` });
const medPolicySnapshot = (id: string): AdminPolicySetSummary => ({ id, platform: medwayPlatform, name: "Policy snapshot", version: 1, effectiveFrom: "2026-01-01T00:00:00.000Z", effectiveTo: null, status: "active", documentReference: `${id}-snapshot-redacted` });
const medOwner = (n: number) => n === 3 ? { type: "organization" as const, organizationId: "med-org-001", displayName: "BUC Medicine Group" } : { type: "user" as const, userId: `med-user-00${n}`, displayName: medStudents[n - 1].displayName ?? "Student profile" };

const medPayments: AdminPaymentDetail[] = [1, 2, 3].map((n) => ({ id: `med-payment-00${n}`, platform: medwayPlatform, orderId: `med-order-00${n}`, status: n === 1 ? "pending_review" : "confirmed", method: n === 2 ? "bank_transfer" : "card", amount: n === 3 ? 2400 : 1800, currency: "EGP", confirmedAt: n === 1 ? null : medDate, evidence: [{ platform: medwayPlatform, paymentId: `med-payment-00${n}`, status: n === 1 ? "under_review" : "accepted", claimedAmount: n === 3 ? 2400 : 1800, currency: "EGP", submittedAt: medDate, reference: { evidenceId: `med-evidence-00${n}`, label: "Redacted payment evidence", submittedAt: medDate, redaction: "private_evidence_reference" }, storage: privateRef(`med-private-payment-evidence-00${n}`) }], transactions: [{ id: `med-transaction-00${n}`, platform: medwayPlatform, paymentId: `med-payment-00${n}`, transactionType: n === 1 ? "manual_review" : "confirmation", status: n === 1 ? "pending" : "succeeded", amount: n === 3 ? 2400 : 1800, currency: "EGP", processedAt: n === 1 ? null : medDate, providerReferenceRedacted: `med-provider-ref-redacted-${n}` }] }));
const medRefunds: AdminRefundDetail[] = [1, 2].map((n) => ({ id: `med-refund-00${n}`, platform: medwayPlatform, paymentId: `med-payment-00${n}`, status: n === 1 ? "requested" : "completed", amount: n === 1 ? 1800 : 900, currency: "EGP", requestedAt: medDate, reasonCode: n === 1 ? "access-impact-review-pending" : "duplicate-payment", processedAt: n === 1 ? null : medDate, policySnapshot: { id: "med-policy-003", platform: medwayPlatform, name: "Refund policy", version: 1, effectiveFrom: "2026-01-01T00:00:00.000Z", effectiveTo: null, status: "active", documentReference: "med-policy-003-snapshot-redacted" } }));

const medSubscriptions: AdminSubscriptionDetail[] = [1, 2, 3].map((n) => ({ id: `med-subscription-00${n}`, platform: medwayPlatform, owner: medOwner(n), kind: n === 3 ? "group" : n === 2 ? "duo" : "individual", status: n === 2 ? "past_due" : "active", startsAt: "2026-08-01T00:00:00.000Z", endsAt: "2027-08-01T00:00:00.000Z", renewsAt: "2027-08-01T00:00:00.000Z", activeSeatCount: n === 3 ? 1 : 0, terms: { planId: `med-plan-00${n}`, currency: "EGP", policySnapshot: { id: `med-policy-00${Math.min(n, 3)}`, platform: medwayPlatform, name: "Commercial policy", version: 1, effectiveFrom: "2026-01-01T00:00:00.000Z", effectiveTo: null, status: "active", documentReference: `med-policy-00${Math.min(n, 3)}-snapshot-redacted` }, termsReferenceRedacted: `med-terms-redacted-${n}` }, seats: n === 3 ? [{ id: "med-seat-001", platform: medwayPlatform, subscriptionId: `med-subscription-00${n}`, status: "assigned", assignedUserId: "med-user-003", assignedAt: medDate, revokedAt: null }] : [], replacements: [] }));
const medSeats: AdminSeatSummary[] = [{ id: "med-seat-001", platform: medwayPlatform, subscriptionId: "med-subscription-003", status: "assigned", assignedUserId: "med-user-003", assignedAt: medDate, revokedAt: null }];
const medGrants: AdminAccessGrantDetail[] = [1, 2, 3, 4].map((n) => ({ id: `med-grant-00${n}`, platform: medwayPlatform, recipientUserId: `med-user-00${n}`, source: { type: n === 3 ? "seat" : "subscription", id: n === 3 ? "med-seat-001" : `med-subscription-00${Math.min(n, 3)}`, displayLabel: "Platform entitlement source", status: n === 4 ? "revoked" : "active" }, scope: { type: n === 2 ? "lesson" : "program", id: n === 2 ? "med-lesson-ana-001" : "med-program-buc", displayLabel: n === 2 ? "Embryology 1" : "BUC Medicine" }, status: n === 4 ? "revoked" : n === 3 ? "suspended" : "active", validFrom: "2026-08-01T00:00:00.000Z", validUntil: "2027-08-01T00:00:00.000Z", revokedAt: n === 4 ? medDate : null, policySnapshot: medPolicySnapshot("med-policy-001"), decisionSnapshotRedacted: { sourceEvaluated: true, redaction: "decision_snapshot_redacted" } }));

const subjectAna: AdminContentTreeNode = { id: "med-subject-ana", platform: medwayPlatform, nodeType: "subject", title: "1102 ANA 🩻 / Anatomy", code: "1102-ANA", status: "published", sequence: 1, children: [
  { id: "med-module-embryology", platform: medwayPlatform, nodeType: "module", title: "Embryology", status: "published", sequence: 1, children: [{ id: "med-chapter-first-weeks", platform: medwayPlatform, nodeType: "chapter", title: "First Weeks Development", status: "published", sequence: 1, children: [1, 2, 3].map((n) => ({ id: `med-lesson-ana-00${n}`, platform: medwayPlatform, nodeType: "lesson", title: `Embryology ${n} — Events of the ${n === 1 ? "First" : n === 2 ? "Second" : "Third"} Week`, status: n === 3 ? "draft" : "published", sequence: n })) }] },
  { id: "med-module-systems-anatomy", platform: medwayPlatform, nodeType: "module", title: "Systems Anatomy", status: "published", sequence: 2, children: ["Cardiovascular System", "Respiratory System", "Digestive System", "Urogenital System"].map((title, n) => ({ id: `med-chapter-systems-00${n + 1}`, platform: medwayPlatform, nodeType: "chapter", title, status: "published" as const, sequence: n + 1 })) },
] };
const medSemesterOne: AdminContentTreeNode = { id: "med-semester-001", platform: medwayPlatform, nodeType: "semester", title: "Semester 1", status: "published", sequence: 1, children: [subjectAna, ...["1104 BIO 🧪 / Biology", "1107 SIM 💉 / Simulation", "1106 ECX 🏥 / Clinical/Exam Context", "Study Plan", "Exam Schedule"].map((title, n) => ({ id: `med-sem1-node-00${n + 2}`, platform: medwayPlatform, nodeType: title === "Study Plan" || title === "Exam Schedule" ? "lesson" as const : "subject" as const, title, status: "published" as const, sequence: n + 2 }))] };
const medContentTree: AdminContentTreeNode[] = [{ id: "med-program-buc", platform: medwayPlatform, nodeType: "program", title: "BUC Medicine", status: "published", children: [
  { id: "med-level-1", platform: medwayPlatform, nodeType: "academic_year", title: "Level 1", status: "published", children: [medSemesterOne, { id: "med-semester-002", platform: medwayPlatform, nodeType: "semester", title: "Semester 2", status: "published", sequence: 2 }] },
  { id: "med-level-2", platform: medwayPlatform, nodeType: "academic_year", title: "Level 2", status: "published", children: ["Semester 3", "Semester 4"].map((title, n) => ({ id: `med-level2-sem-00${n + 3}`, platform: medwayPlatform, nodeType: "semester" as const, title, status: "published" as const })) },
  { id: "med-level-3", platform: medwayPlatform, nodeType: "academic_year", title: "Level 3", status: "published", children: ["Semester 5", "Semester 6"].map((title, n) => ({ id: `med-level3-sem-00${n + 5}`, platform: medwayPlatform, nodeType: "semester" as const, title, status: "published" as const })) },
  { id: "med-extra-resources", platform: medwayPlatform, nodeType: "module", title: "Extra Resources", status: "published" },
] }];
const medLesson = (id: string, title: string, resources: AdminLessonDetail["resources"], status: AdminLessonDetail["status"] = "published"): AdminLessonDetail => ({ id, platform: medwayPlatform, title, status, hierarchyPath: [medContentTree[0], subjectAna], resources, releaseRules: [{ id: `${id}-release`, platform: medwayPlatform, targetId: id, releaseMode: status === "draft" ? "absolute_calendar" : "immediate", status: status === "draft" ? "draft" : "active", availableFrom: status === "draft" ? "2026-09-01T00:00:00.000Z" : null, availableUntil: null, timezone: "Africa/Cairo", policySnapshot: medPolicySnapshot("med-policy-001") }] });
const medLessons: AdminLessonDetail[] = [
  medLesson("med-lesson-ana-001", "Embryology 1 — Events of the First Week", [{ id: "med-resource-ana-001", platform: medwayPlatform, lessonId: "med-lesson-ana-001", resourceType: "document", title: "Lecture PDF", status: "published", sequence: 1, privateStorageReference: privateRef("med-private-doc-ana-lecture-001") }, { id: "med-resource-ana-002", platform: medwayPlatform, lessonId: "med-lesson-ana-001", resourceType: "video", title: "Lecture recording", status: "published", sequence: 2 }]),
  medLesson("med-lesson-ana-002", "Embryology 2 — Events of the Second Week", [{ id: "med-resource-ana-003", platform: medwayPlatform, lessonId: "med-lesson-ana-002", resourceType: "document", title: "PPTX lecture file", status: "published", sequence: 1, privateStorageReference: privateRef("med-private-pptx-ana-002") }]),
  medLesson("med-lesson-ana-003", "Embryology 3 — Events of the Third Week", [{ id: "med-resource-ana-004", platform: medwayPlatform, lessonId: "med-lesson-ana-003", resourceType: "quiz", title: "Question Banks", status: "published", sequence: 1 }], "draft"),
  medLesson("med-lesson-extra-001", "Clinical Medicine Reference", [{ id: "med-resource-extra-001", platform: medwayPlatform, lessonId: "med-lesson-extra-001", resourceType: "file", title: "Protected reference PDF", status: "published", sequence: 1, privateStorageReference: privateRef("med-private-extra-clinical-001") }]),
  medLesson("med-lesson-practical-001", "Anatomy Practical Exam", [{ id: "med-resource-practical-001", platform: medwayPlatform, lessonId: "med-lesson-practical-001", resourceType: "quiz", title: "Practical Exam", status: "published", sequence: 1 }]),
];
const medMediaAssets: AdminMediaAssetDetail[] = [{ id: "med-asset-video-001", platform: medwayPlatform, assetType: "video", resourceId: "med-resource-ana-002", title: "Embryology lecture recording", status: "active", contentHashRedacted: "med-content-hash-redacted-001", privateStorageReference: privateRef("med-private-video-001") }, { id: "med-asset-doc-001", platform: medwayPlatform, assetType: "document", resourceId: "med-resource-ana-001", title: "Anatomy lecture PDF", status: "active", deliveryMode: "watermarked_view", privateStorageReference: privateRef("med-private-doc-ana-lecture-001") }, { id: "med-asset-doc-002", platform: medwayPlatform, assetType: "document", resourceId: "med-resource-extra-001", title: "Clinical Medicine reference", status: "active", deliveryMode: "view_only", privateStorageReference: privateRef("med-private-extra-clinical-001") }];
const medDecisions: AdminAccessDecisionSummary[] = [{ id: "med-decision-001", platform: medwayPlatform, userId: "med-user-001", resourceId: "med-resource-ana-001", result: "allow", reasonCode: "access_granted", evaluatedAt: medDate, grantId: "med-grant-001" }, { id: "med-decision-002", platform: medwayPlatform, userId: "med-user-002", resourceId: "med-resource-ana-003", result: "deny", reasonCode: "content_unreleased", evaluatedAt: medDate, grantId: "med-grant-002" }, { id: "med-decision-003", platform: medwayPlatform, userId: "med-user-003", resourceId: "med-resource-extra-001", result: "deny", reasonCode: "grant_missing", evaluatedAt: medDate, grantId: null }, { id: "med-decision-004", platform: medwayPlatform, userId: "med-user-002", resourceId: "med-resource-ana-002", result: "deny", reasonCode: "concurrency_denied", evaluatedAt: medDate, grantId: "med-grant-002" }, { id: "med-decision-005", platform: medwayPlatform, userId: "med-user-004", resourceId: "med-resource-ana-001", result: "deny", reasonCode: "session_invalid", evaluatedAt: medDate, grantId: null }];
const medPlayback: AdminPlaybackSessionSummary[] = [1, 2, 3].map((n) => ({ id: `med-playback-00${n}`, platform: medwayPlatform, userId: n === 2 ? "med-user-002" : "med-user-001", assetId: "med-asset-video-001", status: n === 2 ? "active" : n === 3 ? "revoked" : "ended", issuedAt: medDate, expiresAt: "2026-08-19T12:00:00.000Z", endedAt: n === 1 ? medDate : null }));
const medAssessments: AdminAssessmentDetail[] = [{ id: "med-assessment-001", platform: medwayPlatform, title: "Anatomy Question Bank", kind: "lesson_quiz", status: "published", questionCount: 40, quizId: "med-quiz-001", availableFrom: null, availableUntil: null, questionBankItems: [{ id: "med-qbank-001", platform: medwayPlatform, questionType: "single_choice", implementationStatus: "active", titleRedacted: "Embryology item", version: 1 }] }, { id: "med-assessment-002", platform: medwayPlatform, title: "Anatomy Practical Exam", kind: "scheduled_exam", status: "published", questionCount: 12, quizId: null, availableFrom: "2026-09-10T08:00:00.000Z", availableUntil: "2026-09-10T12:00:00.000Z", questionBankItems: [] }, { id: "med-assessment-003", platform: medwayPlatform, title: "Clinical Context Review", kind: "lesson_quiz", status: "draft", questionCount: 8, quizId: "med-quiz-003", availableFrom: null, availableUntil: null, questionBankItems: [{ id: "med-qbank-003", platform: medwayPlatform, questionType: "short_answer", implementationStatus: "future_placeholder", version: 1 }] }];
const medAttempts: AdminAttemptDetail[] = [1, 2, 3, 4, 5].map((n) => ({ id: `med-attempt-00${n}`, platform: medwayPlatform, assessmentId: n === 2 ? "med-assessment-002" : "med-assessment-001", studentUserId: `med-user-00${(n % 4) + 1}`, enrollmentId: n === 2 ? null : `med-enrollment-00${(n % 3) + 1}`, status: n === 1 ? "awaiting_review" : n === 2 ? "submitted" : n === 5 ? "invalidated" : "scored", startedAt: medDate, submittedAt: n === 1 ? null : medDate, score: n === 5 ? null : 82, assessmentVersion: "v1", answerCount: n === 2 ? 12 : 40, reviewState: n === 1 ? "manual_review" : "released" }));
const medAudit: AdminAuditLogItem[] = [1, 2, 3, 4, 5, 6].map((n) => ({ id: `med-audit-00${n}`, platform: medwayPlatform, occurredAt: medDate, actorType: "admin", actorId: "med-admin-001", action: ["payment_review", "grant_issued", "lesson_published", "device_revoked", "attempt_invalidated", "refund_requested"][n - 1], entityType: "platform_record", entityId: `med-record-00${n}`, beforeReference: null, afterReference: `med-audit-after-redacted-${n}`, correlationId: `med-correlation-00${n}` }));
const medSecurity: AdminSecurityEventItem[] = [1, 2, 3, 4, 5].map((n) => ({ id: `med-security-00${n}`, platform: medwayPlatform, eventType: n === 1 ? "access_denied" : n === 2 ? "device" : "session", occurredAt: medDate, userId: `med-user-00${(n % 4) + 1}`, sessionId: `med-session-00${(n % 4) + 1}`, severity: n === 1 || n === 2 ? "warning" : "info", metadataReference: `med-security-metadata-redacted-${n}` }));
const medAdminActions: AdminAdminActionItem[] = [1, 2, 3, 4].map((n) => ({ id: `med-admin-action-00${n}`, platform: medwayPlatform, adminUserId: "med-admin-001", actionType: ["review_payment", "revoke_device", "publish_lesson", "invalidate_attempt"][n - 1], targetEntityType: "platform_record", targetEntityId: `med-record-00${n}`, authorizationReference: `med-authz-redacted-${n}`, occurredAt: medDate, outcome: "succeeded" }));
const medRoles: AdminRoleSummary[] = ["platform_support", "content_editor", "finance_reviewer"].map((code, n) => ({ id: `med-role-00${n + 1}`, platform: medwayPlatform, code, name: code.replace("_", " "), permissionCodes: n === 0 ? ["admin.students.read", "admin.sessions.revoke", "admin.devices.revoke"] : n === 1 ? ["admin.content.read", "admin.content.publish", "admin.content.withdraw"] : ["admin.payments.read", "admin.payments.review", "admin.refunds.read", "admin.refunds.decide"], status: "active" }));
const medAdminUsers: AdminUserSummary[] = [1, 2, 3].map((n) => ({ id: `med-admin-00${n}`, platform: medwayPlatform, appUserId: `med-user-00${n}`, displayName: ["Medway Support", "Medway Content", "Medway Finance"][n - 1], emailMasked: `admin${n}@m***.edu`, status: "active", elevatedAccessExpiresAt: null, roleIds: [`med-role-00${n}`] }));

const eliteStudents: AdminStudentDetail[] = [{ id: "elite-user-001", platform: elitePlatform, displayName: "Elite Learner One", emailMasked: "learner1@e***.edu", phoneMasked: "+20 *** *** **1", academicTermOrYear: "Foundation Track", university: "Elite Medical Academy", studentIdMasked: "ELT-****-1", status: "active", activeSubscriptionCount: 1, activeGrantCount: 1, activeDeviceCount: 1, activeSessionCount: 1, lastSeenAt: eliteDate, riskFlags: ["none"], createdAt: "2026-07-01T09:00:00.000Z", access: { activeSubscriptionCount: 1, activeSeatCount: 0, activeGrantCount: 1, expiredGrantCount: 0, revokedGrantCount: 0, enrollmentCount: 1 }, learning: { enrollmentCount: 1, completedLessonCount: 2, attemptCount: 1, playbackSessionCount: 1, lastLearningActivityAt: eliteDate }, devices: [], sessions: [] }, { id: "elite-user-002", platform: elitePlatform, displayName: "Elite Learner Two", emailMasked: "learner2@e***.edu", status: "active", activeSubscriptionCount: 1, activeGrantCount: 1, activeDeviceCount: 1, activeSessionCount: 1, lastSeenAt: eliteDate, riskFlags: ["none"], createdAt: "2026-07-01T09:00:00.000Z", access: { activeSubscriptionCount: 1, activeSeatCount: 0, activeGrantCount: 1, expiredGrantCount: 0, revokedGrantCount: 0, enrollmentCount: 1 }, learning: { enrollmentCount: 1, completedLessonCount: 1, attemptCount: 1, playbackSessionCount: 1, lastLearningActivityAt: eliteDate }, devices: [], sessions: [] }];
const eliteDevices: AdminDeviceSummary[] = [{ id: "elite-device-001", platform: elitePlatform, userId: "elite-user-001", deviceLabel: "Elite browser", deviceType: "browser", trustStatus: "recognized", fingerprintReference: "elite-fingerprint-redacted-001" }];
const eliteSessions: AdminSessionSummary[] = [{ id: "elite-session-001", platform: elitePlatform, userId: "elite-user-001", deviceId: "elite-device-001", status: "active", issuedAt: eliteDate, expiresAt: "2026-08-19T20:00:00.000Z", lastActivityAt: eliteDate }];
const elitePolicy: AdminPolicySetSummary = { id: "elite-policy-001", platform: elitePlatform, name: "Elite access policy", version: 1, effectiveFrom: "2026-01-01T00:00:00.000Z", effectiveTo: null, status: "active", documentReference: "elite-policy-document-redacted" };
const eliteSubscriptions: AdminSubscriptionDetail[] = [{ id: "elite-subscription-001", platform: elitePlatform, owner: { type: "user", userId: "elite-user-001", displayName: "Elite Learner One" }, kind: "individual", status: "active", startsAt: "2026-08-01T00:00:00.000Z", endsAt: "2027-08-01T00:00:00.000Z", renewsAt: null, activeSeatCount: 0, terms: { planId: "elite-plan-001", currency: "EGP", policySnapshot: elitePolicy } , seats: [], replacements: [] }];
const elitePayments: AdminPaymentDetail[] = [{ id: "elite-payment-001", platform: elitePlatform, orderId: "elite-order-001", status: "confirmed", method: "card", amount: 3200, currency: "EGP", confirmedAt: eliteDate, evidence: [], transactions: [{ id: "elite-transaction-001", platform: elitePlatform, paymentId: "elite-payment-001", transactionType: "confirmation", status: "succeeded", amount: 3200, currency: "EGP", processedAt: eliteDate, providerReferenceRedacted: "elite-provider-ref-redacted-001" }] }];
const eliteRefunds: AdminRefundDetail[] = [{ id: "elite-refund-001", platform: elitePlatform, paymentId: "elite-payment-001", status: "rejected", amount: 400, currency: "EGP", requestedAt: eliteDate, reasonCode: "policy_not_eligible", processedAt: null }];
const eliteGrants: AdminAccessGrantDetail[] = [{ id: "elite-grant-001", platform: elitePlatform, recipientUserId: "elite-user-001", source: { type: "subscription", id: "elite-subscription-001", status: "active" }, scope: { type: "program", id: "elite-program-001", displayLabel: "Elite Clinical Foundations" }, status: "active", validFrom: "2026-08-01T00:00:00.000Z", validUntil: "2027-08-01T00:00:00.000Z", revokedAt: null, policySnapshot: elitePolicy }];
const eliteContentTree: AdminContentTreeNode[] = [{ id: "elite-program-001", platform: elitePlatform, nodeType: "program", title: "Elite Clinical Foundations", status: "published", children: [{ id: "elite-track-001", platform: elitePlatform, nodeType: "academic_year", title: "Clinical Core", status: "published", children: [{ id: "elite-module-001", platform: elitePlatform, nodeType: "module", title: "Case-Based Learning", status: "published" }] }] }];
const eliteLessons: AdminLessonDetail[] = [{ id: "elite-lesson-001", platform: elitePlatform, title: "Clinical Reasoning Case 1", status: "published", hierarchyPath: eliteContentTree, resources: [{ id: "elite-resource-001", platform: elitePlatform, lessonId: "elite-lesson-001", resourceType: "document", title: "Case brief", status: "published", sequence: 1, privateStorageReference: privateRef("elite-private-case-001") }], releaseRules: [{ id: "elite-release-001", platform: elitePlatform, targetId: "elite-lesson-001", releaseMode: "immediate", status: "active" }] }];
const eliteAssets: AdminMediaAssetDetail[] = [{ id: "elite-asset-001", platform: elitePlatform, assetType: "document", resourceId: "elite-resource-001", title: "Case brief", status: "active", privateStorageReference: privateRef("elite-private-case-001"), deliveryMode: "watermarked_view" }];
const eliteDecisions: AdminAccessDecisionSummary[] = [{ id: "elite-decision-001", platform: elitePlatform, userId: "elite-user-001", resourceId: "elite-resource-001", result: "allow", reasonCode: "access_granted", evaluatedAt: eliteDate, grantId: "elite-grant-001" }];
const elitePlayback: AdminPlaybackSessionSummary[] = [{ id: "elite-playback-001", platform: elitePlatform, userId: "elite-user-001", assetId: "elite-asset-001", status: "active", issuedAt: eliteDate, expiresAt: "2026-08-19T12:00:00.000Z" }];
const eliteAssessments: AdminAssessmentDetail[] = [{ id: "elite-assessment-001", platform: elitePlatform, title: "Elite Case Review", kind: "lesson_quiz", status: "published", questionCount: 10, questionBankItems: [] }];
const eliteAttempts: AdminAttemptDetail[] = [{ id: "elite-attempt-001", platform: elitePlatform, assessmentId: "elite-assessment-001", studentUserId: "elite-user-001", enrollmentId: null, status: "scored", startedAt: eliteDate, submittedAt: eliteDate, score: 91, answerCount: 10 }];
const eliteAudit: AdminAuditLogItem[] = [{ id: "elite-audit-001", platform: elitePlatform, occurredAt: eliteDate, actorType: "admin", actorId: "elite-admin-001", action: "assessment_published", entityType: "assessment", entityId: "elite-assessment-001", correlationId: "elite-correlation-001" }];
const eliteSecurity: AdminSecurityEventItem[] = [{ id: "elite-security-001", platform: elitePlatform, eventType: "authentication", occurredAt: eliteDate, userId: "elite-user-001", severity: "info", metadataReference: "elite-security-redacted-001" }];
const eliteActions: AdminAdminActionItem[] = [{ id: "elite-admin-action-001", platform: elitePlatform, adminUserId: "elite-admin-001", actionType: "publish_assessment", targetEntityType: "assessment", targetEntityId: "elite-assessment-001", authorizationReference: "elite-authz-redacted-001", occurredAt: eliteDate, outcome: "succeeded" }];
const eliteRoles: AdminRoleSummary[] = [{ id: "elite-role-001", platform: elitePlatform, code: "elite_admin", name: "Elite Admin", permissionCodes: ["admin.audit.read", "admin.content.read", "admin.assessments.read"], status: "active" }];
const eliteAdminUsers: AdminUserSummary[] = [{ id: "elite-admin-001", platform: elitePlatform, appUserId: "elite-user-001", displayName: "Elite Admin", emailMasked: "admin@e***.edu", status: "active", roleIds: ["elite-role-001"] }];

export const medwayFixtures: AdminFixtureBundle = { platform: medwayPlatform, overview: medwayOverviewDashboard, students: medStudents, devices: medDevices, sessions: medSessions, payments: medPayments, refunds: medRefunds, subscriptions: medSubscriptions, seats: medSeats, accessGrants: medGrants, contentTree: medContentTree, lessons: medLessons, mediaAssets: medMediaAssets, accessDecisions: medDecisions, playbackSessions: medPlayback, assessments: medAssessments, attempts: medAttempts, auditLogs: medAudit, securityEvents: medSecurity, adminActions: medAdminActions, roles: medRoles, adminUsers: medAdminUsers, policySets: [1, 2, 3].map((n) => medPolicy(n, ["Access policy", "Media policy", "Refund policy"][n - 1])) };
export const eliteFixtures: AdminFixtureBundle = { platform: elitePlatform, overview: eliteOverviewDashboard, students: eliteStudents, devices: eliteDevices, sessions: eliteSessions, payments: elitePayments, refunds: eliteRefunds, subscriptions: eliteSubscriptions, seats: [], accessGrants: eliteGrants, contentTree: eliteContentTree, lessons: eliteLessons, mediaAssets: eliteAssets, accessDecisions: eliteDecisions, playbackSessions: elitePlayback, assessments: eliteAssessments, attempts: eliteAttempts, auditLogs: eliteAudit, securityEvents: eliteSecurity, adminActions: eliteActions, roles: eliteRoles, adminUsers: eliteAdminUsers, policySets: [elitePolicy] };

export const adminFixtureBundles: readonly AdminFixtureBundle[] = [medwayFixtures, eliteFixtures];
