import type { CalendarEvent, AgendaItem, ReminderItem, StudyGoalProgress } from "./calendar.types";

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  // Week of Aug 25–31, 2026
  {
    id: "evt-1",
    title: "Read Quiz",
    type: "quiz",
    date: "2026-09-20",
    startTime: "10:00",
    endTime: "10:45",
    displayTime: "10:00 - 10:45 AM",
    courseTitle: "Biochemistry Fundamentals • Lesson 1",
    description: "Weekly comprehension quiz on biochemical foundations and cellular metabolism.",
    status: "upcoming",
  },
  {
    id: "evt-2",
    title: "Biochemistry Case Review",
    type: "assignment",
    date: "2026-09-20",
    startTime: "13:00",
    endTime: "14:00",
    displayTime: "1:00 - 2:00 PM",
    courseTitle: "Cellular Biology and Genetics",
    description: "Guided review of foundational biochemical pathways and applied questions.",
    status: "upcoming",
  },
  {
    id: "evt-3",
    title: "Personal Study",
    type: "study_block",
    date: "2026-09-16",
    startTime: "16:00",
    endTime: "17:30",
    displayTime: "4:00 - 5:30 PM",
    courseTitle: "Cellular Biology and Genetics",
    description: "Focused study block for cellular structures and histology notes.",
    status: "upcoming",
  },
  {
    id: "evt-4",
    title: "Live Session",
    type: "live_session",
    date: "2026-09-15",
    startTime: "09:00",
    endTime: "10:30",
    displayTime: "9:00 - 10:30 AM",
    courseTitle: "Biochemistry Foundations Live Review",
    locationOrUrl: "https://meet.greenlearn.edu/live-ux-04",
    description: "Interactive live review for Biochemistry Fundamentals.",
    status: "upcoming",
  },
  {
    id: "evt-5",
    title: "Office Hours",
    type: "office_hours",
    date: "2026-09-26",
    startTime: "15:00",
    endTime: "16:00",
    displayTime: "3:00 - 4:00 PM",
    courseTitle: "Human Anatomy & Design Faculty",
    locationOrUrl: "https://meet.greenlearn.edu/office-hours-dr-miller",
    description: "Open Q&A session with Prof. Miller regarding upcoming project milestones.",
    status: "upcoming",
  },
  // Today: 2026-08-30 (Sunday)
  {
    id: "evt-6",
    title: "Read Quiz",
    type: "quiz",
    date: "2026-09-30",
    startTime: "10:00",
    endTime: "10:45",
    displayTime: "10:00 - 10:45 AM",
    courseTitle: "Biochemistry Fundamentals • Lesson 1",
    description: "Quick quiz covering biomolecules, enzymes, and introductory metabolism.",
    status: "upcoming",
  },
  {
    id: "evt-7",
    title: "Personal Study",
    type: "study_block",
    date: "2026-09-30",
    startTime: "14:00",
    endTime: "15:30",
    displayTime: "2:00 - 3:30 PM",
    courseTitle: "Histology Foundations",
    description: "Reviewing histology slides and first-week learning notes.",
    status: "upcoming",
  },
  {
    id: "evt-8",
    title: "Live Session",
    type: "live_session",
    date: "2026-09-30",
    startTime: "18:00",
    endTime: "19:30",
    displayTime: "6:00 - 7:30 PM",
    courseTitle: "Biochemistry Fundamentals",
    locationOrUrl: "https://meet.greenlearn.edu/live-ux-evening",
    description: "Live Biochemistry Fundamentals review and Q&A.",
    status: "upcoming",
  },
  {
    id: "evt-9",
    title: "Biochemistry Case Review",
    type: "assignment",
    date: "2026-09-28",
    startTime: "11:00",
    endTime: "12:00",
    displayTime: "11:00 AM - 12:00 PM",
    courseTitle: "Cellular Biology and Genetics",
    description: "Review submitted Biochemistry practice questions.",
    status: "upcoming",
  },
  {
    id: "evt-10",
    title: "Read Quiz",
    type: "quiz",
    date: "2026-09-29",
    startTime: "16:00",
    endTime: "16:45",
    displayTime: "4:00 - 4:45 PM",
    courseTitle: "Physiology Foundations • Lesson 1",
    description: "Physiology foundations quiz and short-answer practice.",
    status: "upcoming",
  },
  // Next week: Sep 1–6, 2026
  {
    id: "evt-11",
    title: "Live Session",
    type: "live_session",
    date: "2026-09-18",
    startTime: "09:00",
    endTime: "10:30",
    displayTime: "9:00 - 10:30 AM",
    courseTitle: "Biochemistry Fundamentals",
    locationOrUrl: "https://meet.greenlearn.edu/live-ux-sep01",
    description: "Biochemistry kickoff lecture for Elite Year 1.",
    status: "upcoming",
  },
  {
    id: "evt-12",
    title: "Personal Study",
    type: "study_block",
    date: "2026-09-18",
    startTime: "13:00",
    endTime: "14:30",
    displayTime: "1:00 - 2:30 PM",
    courseTitle: "Cellular Biology and Genetics",
    description: "Cellular Biology and Genetics reading block.",
    status: "upcoming",
  },
  {
    id: "evt-13",
    title: "Office Hours",
    type: "office_hours",
    date: "2026-09-19",
    startTime: "17:00",
    endTime: "18:00",
    displayTime: "5:00 - 6:00 PM",
    courseTitle: "Department Mentorship",
    locationOrUrl: "https://meet.greenlearn.edu/mentorship-weekly",
    description: "1-on-1 career path guidance and resume design clinic.",
    status: "upcoming",
  },
  {
    id: "evt-14",
    title: "Read Quiz",
    type: "quiz",
    date: "2026-09-19",
    startTime: "10:00",
    endTime: "10:45",
    displayTime: "10:00 - 10:45 AM",
    courseTitle: "Anatomy Foundations • Lesson 1",
    description: "Anatomy foundations quiz and terminology review.",
    status: "upcoming",
  },
  {
    id: "evt-15",
    title: "Anatomy Lecture",
    type: "live_session",
    date: "2026-09-20",
    startTime: "11:00",
    endTime: "12:30",
    displayTime: "11:00 AM - 12:30 PM",
    courseTitle: "Human Anatomy",
    locationOrUrl: "https://meet.greenlearn.edu/anatomy-sep05",
    description: "Musculoskeletal system overview with interactive 3D model walkthrough.",
    status: "upcoming",
  },
  {
    id: "evt-16",
    title: "Anatomy Lecture",
    type: "live_session",
    date: "2026-09-16",
    startTime: "11:00",
    endTime: "12:30",
    displayTime: "11:00 AM - 12:30 PM",
    courseTitle: "Human Anatomy",
    locationOrUrl: "https://meet.greenlearn.edu/anatomy-sep05",
    description: "Musculoskeletal system overview with interactive 3D model walkthrough.",
    status: "upcoming",
  },
  {
    id: "evt-17",
    title: "Anatomy assignment",
    type: "assignment",
    date: "2026-09-14",
    startTime: "12:00",
    endTime: "1:30",
    displayTime: "11:00 AM - 12:30 PM",
    courseTitle: "Human Anatomy",
    locationOrUrl: "https://meet.greenlearn.edu/anatomy-sep05",
    description: "Musculoskeletal system overview with interactive 3D model walkthrough.",
    status: "upcoming",
  },
];

export const INITIAL_AGENDA_ITEMS: AgendaItem[] = [
  {
    id: "agenda-1",
    time: "10:00 AM",
    title: "Read Quiz",
    subtitle: "Biochemistry Fundamentals • Lesson 1",
    type: "quiz",
  },
  {
    id: "agenda-2",
    time: "2:00 PM",
    title: "Personal Study",
    subtitle: "Histology Foundations",
    type: "study_block",
  },
  {
    id: "agenda-3",
    time: "6:00 PM",
    title: "Live Session",
    subtitle: "Biochemistry Fundamentals",
    type: "live_session",
    hasAction: true,
    actionLabel: "Join",
    linkUrl: "https://meet.greenlearn.edu/live-ux-evening",
  },
];

export const INITIAL_STUDY_GOAL: StudyGoalProgress = {
  weeklyPercentage: 75,
  completedHours: 9,
  targetHours: 12,
  streakDays: [
    { day: "S", completed: true },
    { day: "M", completed: true },
    { day: "T", completed: true },
    { day: "W", completed: true },
    { day: "T", completed: true },
    { day: "F", completed: true },
    { day: "S", completed: true, isCurrent: true },
  ],
};

export const INITIAL_REMINDERS: ReminderItem[] = [
  {
    id: "rem-1",
    title: "Biochemistry Case Review",
    dateLabel: "Aug 30, 2:00 PM",
    type: "assignment",
    completed: false,
  },
  {
    id: "rem-2",
    title: "Weekly Goal Check-in",
    dateLabel: "Sep 5, End of day",
    type: "goal",
    completed: false,
  },
  {
    id: "rem-3",
    title: "Anatomy Foundations Quiz",
    dateLabel: "Sep 4, 10:00 AM",
    type: "quiz",
    completed: false,
  },
];
